<?php

/**
 * @var \STBDigital\Zoones\Block\Index $block
 */

$result = $block->getItems();
?>
<div class="section">
    <div class="container">
        <div class="row">
            <?php if ($result['valid']) { ?>
                <div class="col-12">
                    <div class="zoones-orderstatus__summary zoones-orderstatus__summary--top bg-primary">
                        <div class="zoones-orderstatus__summary__item">
                            <?php if (count($result["items"])) { ?>
                                <span><?php echo __("zoones.currentstatus")?></span><b><?= $result['currentStatus']; ?></b>
                            <?php } else { ?>
                                <span><?php echo __("zoones.noresults")?></span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="zoones-orderstatus__summary">
                        <div class="zoones-orderstatus__summary__item">
                            <span><?php echo __("zoones.reference")?></span><b><?= $result['reference']; ?></b>
                        </div>
                        <div class="zoones-orderstatus__summary__item">
                            <span><?php echo __("zoones.zipcode")?></span><b><?= $result['zip']; ?></b>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <div class="col-12 col-lg-6">
                <form id="orderStatusForm">
                    <div class="form-group">
                        <label for="reference"><?php echo __("zoones.reference")?></label>
                        <input required="required" type="text" name="reference"
                               value="<?= $result['valid'] ? $result['reference'] : '' ?>"
                               class="form-control mb-1">
                    </div>
                    <div class="form-group">
                        <label for="zip"><?php echo __("zoones.zipcode")?></label>
                        <input required="required" type="text" name="zip"
                               value="<?= $result['valid'] ? $result['zip'] : '' ?>"
                               class="form-control mb-2">
                    </div>
                    <input type="submit" class="btn btn-primary" value="<?php echo __("zoones.checkorder")?>">
                </form>
            </div>
            <?php if ($result['valid'] && count($result["items"])) { ?>
                <div class="col-12 col-lg-6">
                    <div class="zoones-orderstatus__history">
                        <h5 class="text-uppercase"><?php echo __("zoones.history")?></h5>
                        <ul class="zoones-orderstatus__list list-unstyled">
                            <?php foreach ($result['items'] as $item) { ?>
                                <li class="zoones-orderstatus__listitem">
                                    <div class="zoones-orderstatus__icon">
                                        <i class="<?= $item['iconClass']; ?>"></i>
                                    </div>
                                    <div class="zoones-orderstatus__info">
                                        <b><?= $item['status']; ?></b>
                                        <?php if ($item['timeStamp']) { ?>
                                            <span><?= $item['timeStamp']; ?></span>
                                        <?php } ?>
                                        <span><?= $item['description']; ?></span>
                                    </div>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
